-- Loads the CSVs generated by scripts/generate_data.py into DuckDB.
-- Run scripts/generate_data.py first, and run 01_create_schema.sql before this.

COPY employee FROM 'data/employee.csv' (HEADER, AUTO_DETECT TRUE);
COPY customer FROM 'data/customer.csv' (HEADER, AUTO_DETECT TRUE);
COPY tickets FROM 'data/tickets.csv' (HEADER, AUTO_DETECT TRUE);
COPY ticket_notes FROM 'data/ticket_notes.csv' (HEADER, AUTO_DETECT TRUE);

-- Sanity check: row counts across all four tables.
SELECT
    (SELECT COUNT(*) FROM employee)     AS employee_count,
    (SELECT COUNT(*) FROM customer)     AS customer_count,
    (SELECT COUNT(*) FROM tickets)      AS ticket_count,
    (SELECT COUNT(*) FROM ticket_notes) AS ticket_note_count;
