-- Loads the CSVs generated by scripts/generate_data.py into DuckDB.
-- Run scripts/generate_data.py first, and run 01_create_schema.sql before this.

COPY tickets FROM 'data/tickets.csv' (HEADER, AUTO_DETECT TRUE);
COPY ticket_notes FROM 'data/ticket_notes.csv' (HEADER, AUTO_DETECT TRUE);

-- Sanity check: should print 10,000 tickets and however many notes were generated.
SELECT
    (SELECT COUNT(*) FROM tickets)      AS ticket_count,
    (SELECT COUNT(*) FROM ticket_notes) AS ticket_note_count;
